# Generated by Django 3.0.4 on 2020-04-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('name', models.CharField(default='region', max_length=255)),
                ('avgAge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avgDailyIncomeInUSD', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('avgDailyIncomePopulation', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('periodType', models.CharField(default='days', max_length=50)),
                ('timeToElapse', models.CharField(default=0, max_length=255)),
                ('reportedCases', models.CharField(default=0, max_length=255)),
                ('population', models.CharField(default=0, max_length=255)),
                ('totalHospitalBeds', models.CharField(default=0, max_length=255)),
            ],
        ),
    ]
